name: Build & Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: multi-k8s-478410
  REGION: europe-central2
  REGISTRY: europe-central2-docker.pkg.dev/multi-k8s-478410/multi-container-registry
  CLUSTER_NAME: ardin-k8ss
  SHA: ${{ github.sha }}

jobs:

  build:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth GCloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      # ---- BUILD WITH BOTH TAGS ----
      - name: Build images
        run: |
          docker build -t $REGISTRY/client:latest -t $REGISTRY/client:${SHA} ./client
          docker build -t $REGISTRY/server:latest -t $REGISTRY/server:${SHA} ./server
          docker build -t $REGISTRY/worker:latest -t $REGISTRY/worker:${SHA} ./worker

      # ---- PUSH BOTH TAGS ----
      - name: Push images
        run: |
          docker push $REGISTRY/client:latest
          docker push $REGISTRY/client:${SHA}

          docker push $REGISTRY/server:latest
          docker push $REGISTRY/server:${SHA}

          docker push $REGISTRY/worker:latest
          docker push $REGISTRY/worker:${SHA}

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth GCloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.REGION }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Apply Kubernetes Manifests
        run: kubectl apply -f Kubernetes/

      # ---- DEPLOY USING SHA ----
      - name: Update deployments
        run: |
          kubectl set image deployment/client-deployment client=$REGISTRY/client:${SHA}
          kubectl set image deployment/server-deployment server=$REGISTRY/server:${SHA}
          kubectl set image deployment/worker-deployment worker=$REGISTRY/worker:${SHA}

